gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include("member.urls"), name="member"),
    path('trainer/', include("trainer.urls"), name="trainer"),
    path('pack/', include("pack.urls"), name="pack"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from member.views import Create, MemberList, MemberDetail


urlpatterns = [
    path("login/", 
        auth_views.LoginView.as_view(template_name="member/home.html"), 
        name="member-login"),
    path("create/", Create.as_view(), name="member-create"),
    path("list/", MemberList.as_view(), name="member-list"),
    path("view/<int:pk>", MemberDetail.as_view(), name="member-detail"),
]

member/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
from PIL import Image


class Member(models.Model):
    # Mobile Number Validator
    phone_regex = RegexValidator(regex=r'^\+?1?\d{12}$',
                                 message="Phone number must be entered in the format: "
                                         " '+999999999'. Up to 10 digits allowed. "
                                         "Country Code with (+) Sign Required")

    # Choices for Sex List
    s = [("m", "Male"), ("f", "Female")]

    # Fields of Member Model
    first_name = models.CharField(max_length=50, blank=False, null=False)

    last_name = models.CharField(max_length=50, blank=False, null=False)

    mobile_one = models.CharField(unique=True,
                                  validators=[phone_regex],
                                  max_length=13,
                                  help_text="+911234567890")  # validators should be a list

    mobile_two = models.CharField(validators=[phone_regex],
                                  max_length=13,
                                  blank=True)

    sex = models.CharField(max_length=1, choices=s, default="f")

    address = models.TextField(blank=True,
                               max_length=300,
                               help_text="Maximum 300 Characters only")

    profession = models.CharField(blank=True,
                                  max_length=30,
                                  help_text="Maximum 30 Characters only")

    email = models.EmailField(max_length=100, blank=True)

    marriage = models.DateField(null=True, blank=True)

    dob = models.DateField(null=True, blank=True)

    pic = models.ImageField(default="default.png",
                            upload_to="profile_pics",
                            blank=True)

    date_joined = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        super(*args, **kwargs).save(*args, **kwargs)
        img = Image.open(self.pic.path)
        img.thumbnail((286, 180), Image.ANTIALIAS)
        img.save(self.pic.path)

member/forms.py
from django import forms
from django.forms import ModelForm
from .models import Member
from datetime import datetime


class MemberCreateForm(ModelForm):
    s = [("m", "Male"), ("f", "Female")]
    sex = forms.ChoiceField(choices=s, widget=forms.RadioSelect)

    mobile_one = forms.CharField(max_length=13,
                                 label="Mobile Number",
                                 required=True)

    mobile_two = forms.CharField(max_length=13,
                                 label="Mobile Number",
                                 required=False)

    YEARS = [y for y in range(1900, datetime.now().year + 1)]

    # marriage = forms.DateField(label="Marriage Anniversary",
    #                            required=False,
    #                            widget=forms.SelectDateWidget(years=YEARS))

    # dob = forms.DateField(label="Date of Birth",
    #                       required=False,
    #                       widget=forms.SelectDateWidget(years=YEARS))

    marriage = forms.DateField(required=False, widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))

    dob = forms.DateField(required=False, widget=forms.widgets.DateTimeInput(attrs={"type": "date"}))

    pic = forms.ImageField(label="Upload Profile Picture", required=False)

    class Meta:
        model = Member
        fields = ["first_name",
                  "last_name",
                  "sex",
                  "mobile_one",
                  "mobile_two",
                  "email",
                  "address",
                  "profession",
                  "marriage",
                  "dob",
                  "pic", ]

member/views.py
from django.shortcuts import render, redirect
from .forms import MemberCreateForm
from django.contrib import messages
from django.views.generic import View, ListView, DetailView
from .models import Member


class Create(View):
    form = MemberCreateForm()
    extra_context = {"form": form}
    template_name = "member/create.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.extra_context)

    def post(self, request, *args, **kwargs):
        self.form = MemberCreateForm(request.POST, request.FILES, *args, **kwargs)
        if self.form.is_valid():
            self.form.save(*args, **kwargs)
            messages.success(request, f"Account for {self.form.cleaned_data['first_name']} "
                                      f"has been created, Login to Continue ...")

            return redirect("member-list")
        else:
            return render(request, self.template_name, {"form": self.form})


class MemberList(ListView):
    model = Member
    template_name = "member/member_list.html"


class MemberDetail(DetailView):
    model = Member
    template_name = "member/member_detail.html"

member/templates/member/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row justify-content-center">
    <div style="background:transparent !important" class="col col-9 jumbotron font-weight-lighter">
        <h3 class="text-center ">Create New Member</h3>
        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form|crispy }}
            <div class="col col-4">
<img id='img-upload' style="width: 100%" /></div>
            <div class="form-group text-center">
                <input class="btn btn-primary" type="submit" value="Register"/>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready( function() {
        $(document).on('change', '.clearablefileinput :file', function() {
        var input = $(this),
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.trigger('fileselect', [label]);
        });

        $('.clearablefileinput :file').on('fileselect', function(event, label) {
            
            var input = $(this).parents('.input-group').find(':text'),
                log = label;
            
            if( input.length ) {
                input.val(log);
            } else {
                if( log ) alert(log);
            }
        
        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                
                reader.onload = function (e) {
                    $('#img-upload').attr('src', e.target.result);
                }
                
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#id_pic").change(function(){
            readURL(this);
        });     
    });
</script>
{% endblock content %}

member/templates/member/home.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}

<div class="row justify-content-center">
    <div class="col col-9 jumbotron font-weight-lighter">
        <h3 class="text-center ">Login</h3>
        <form method="POST">

            {% csrf_token %}
            {{ form|crispy }}

            <div class="form-group text-center">
                <input class="btn btn-primary" type="submit" value="LogIn"/>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

member/templates/member/member_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row justify-content-center">
    <div class="col col-md-6 col-sm-6 col-lg-4">


        <div class="card" style="width: 18rem;">
        <h3 class="text-center">{{ object.first_name }} {{ object.last_name }}</h3><br/>
            <img src="{{ object.pic.url }}"
                 style="align-self: center; width: {{ object.pic.width }}px; height: {{ object.pic.height }}px;"
                 class="card-img" alt="Can't Load Image, Upload New One">



            <div class="card-body">
                <h5 class="card-title">{{ object.first_name }} {{ object.last_name }}</h5>
                <p class="card-text">---------------</p>
            </div>

            <ul class="list-group list-group-flush">

                {% if object.sex == "f" %}
                    <li class="list-group-item">FeMale
                {% else %}
                    <li class="list-group-item">MaLe
                {% endif %}
                <br/>
                <small class="text-muted">Gender</small>
                </li>

                {% if object.mobile_one %}
                <li class="list-group-item">
                    {{ object.mobile_one }}<br/>
                    <small class="text-muted">Primary Contact</small>
                </li>
                {% endif %}

                {% if object.mobile_two %}
                <li class="list-group-item">
                    {{ object.mobile_two }}<br/>
                    <small class="text-muted">Secondary Contact</small>
                </li>
                {% endif %}

                {% if object.email %}
                <li class="list-group-item">
                    {{ object.email }}<br/>
                    <small class="text-muted">EMail Address</small>
                </li>
                {% endif %}

                {% if object.profession %}
                <li class="list-group-item">
                    {{ object.profession }}<br/>
                    <small class="text-muted">: Profession</small>
                </li>
                {% endif %}

                {% if object.address %}
                <li class="list-group-item">
                    {{ object.address }}<br/>
                    <small class="text-muted">: Address</small>
                </li>
                {% endif %}

                {% if object.dob %}
                <li class="list-group-item">
                    {{ object.dob }}<br/>
                    <small class="text-muted">: Date of Birth</small>
                </li>
                {% endif %}

                {% if object.marriage %}
                <li class="list-group-item">
                    {{ object.marriage }}<br/>
                    <small class="text-muted">: Marriage Anniversary</small>
                </li>
                {% endif %}

                {% if object.date_joined %}
                <li class="list-group-item">
                    {{ object.date_joined|date }}<br/>
                    <small class="text-muted">: Joined on</small>
                </li>
                {% endif %}

            </ul>

        </div>


    </div>
</div>

{% endblock content %}

member/templates/member/member_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center ">Members</h3><br/>
<div class="row">
    {% for member in object_list %}
    <div class="col col-md-6 col-lg-4 col-sm-6" style="display: flex; justify-content: center; align-items: center;">
        <div class="card-deck">
            <div class="card border-success mb-5" style="width: 18rem;">
                <div style="width: 18rem; height: 180px; display: flex; justify-content: center; align-items: center;">
                    <img class="card-img-top" src="{{ member.pic.url }}"
                         style="align-self: center; width: {{ member.pic.width }}px; height: {{ member.pic.height }}px;"
                         alt="Card image cap"/>
                </div>
                <div class="card-body">
                    <a href="{% url 'member-detail' member.pk %} "><h5 class="card-title">{{ member.first_name }} {{ member.last_name }}</h5></a>
                    <p class="card-text">
                        {{ member.mobile_one }}<br/>
                        Joined on : {{ member.date_joined.date }}
                    </p>
                    <a href="#" class="btn btn-primary">Link</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}